CREATE TABLE webhook_deliveries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_endpoint_id integer NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
    event text NOT NULL CHECK (event IN ('task.created', 'task.updated', 'task.completed', 'comment.created', 'project.updated')),
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'failed')),
    response_status integer,
    response_body text,
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX webhook_deliveries_endpoint_id_idx ON webhook_deliveries(webhook_endpoint_id);
