CREATE TABLE comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    author_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER comments_set_updated_at BEFORE UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX comments_task_id_idx ON comments(task_id);
