CREATE TABLE tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'todo' CHECK (status IN ('backlog', 'todo', 'in_progress', 'review', 'done')),
    priority text CHECK (priority IS NULL OR priority IN ('low', 'medium', 'high', 'urgent')),
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    creator_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    assignee_id integer REFERENCES users(id) ON DELETE SET NULL,
    due_date date,
    position integer,
    estimate_minutes integer,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tasks_estimate_minutes_non_negative CHECK (estimate_minutes IS NULL OR estimate_minutes >= 0)
);

CREATE TRIGGER tasks_set_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX tasks_project_id_idx ON tasks(project_id);
CREATE INDEX tasks_creator_id_idx ON tasks(creator_id);
CREATE INDEX tasks_assignee_id_idx ON tasks(assignee_id);
CREATE INDEX tasks_status_idx ON tasks(status);
