CREATE TABLE task_assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (task_id, user_id)
);

CREATE INDEX task_assignments_user_id_idx ON task_assignments(user_id);
