CREATE TABLE notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    actor_id integer REFERENCES users(id) ON DELETE SET NULL,
    type text NOT NULL CHECK (type IN ('task_assigned', 'mention', 'task_due', 'project_update', 'system_alert')),
    task_id integer REFERENCES tasks(id) ON DELETE CASCADE,
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX notifications_user_id_created_at_idx ON notifications(user_id, created_at DESC);
CREATE INDEX notifications_unread_idx ON notifications(user_id) WHERE is_read = false;
