CREATE TABLE team_members (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
    joined_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (team_id, user_id)
);

CREATE INDEX team_members_user_id_idx ON team_members(user_id);
