CREATE TABLE activity_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id integer REFERENCES users(id) ON DELETE SET NULL,
    entity_type text NOT NULL,
    entity_id integer NOT NULL,
    action text NOT NULL,
    before jsonb,
    after jsonb,
    ip_address inet,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX activity_logs_entity_idx ON activity_logs(entity_type, entity_id, created_at DESC);
