CREATE TABLE webhook_endpoints (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    secret text NOT NULL,
    events text[] NOT NULL CHECK (events <@ ARRAY['task.created', 'task.updated', 'task.completed', 'comment.created', 'project.updated']::text[]),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER webhook_endpoints_set_updated_at BEFORE UPDATE ON webhook_endpoints FOR EACH ROW EXECUTE FUNCTION set_updated_at();
