CREATE TABLE project_teams (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    team_id integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, team_id)
);

CREATE INDEX project_teams_team_id_idx ON project_teams(team_id);
