CREATE TABLE attachments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    uploader_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    file_name text NOT NULL,
    original_name text NOT NULL,
    storage_key text NOT NULL,
    mime_type text,
    file_size integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT attachments_file_size_non_negative CHECK (file_size IS NULL OR file_size >= 0)
);

CREATE TRIGGER attachments_set_updated_at BEFORE UPDATE ON attachments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX attachments_task_id_idx ON attachments(task_id);
